### ISSUE TITLE
`iroha_wasm` Crate Not Found

### ISSUE THREAD

**Issue by kimpoter** [hyperledger-iroha/iroha-2-docs#512]
https://docs.iroha.tech/blockchain/wasm.html

The `iroha_wasm` crate not found on the repo that referenced on the Cargo.toml file. 

I can't run the `cargo run --release` command to submit and run the smart contract.

![image](https://github.com/user-attachments/assets/5e2d5b18-d69a-4913-bf67-862dcbd643b6)

The following is my `Cargo.toml` file

```toml
[package]
name = "client"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ['cdylib']

[dependencies]
iroha_wasm = { git = "https://github.com/hyperledger-iroha/iroha" }
```
